# Fly.io configuration for Django application
# Deploy with: fly deploy

app = "whsxc"  # Change this to your preferred app name

primary_region = "sjc"  # Change to your preferred region (sjc, iad, lhr, etc.)

[build]
  dockerfile = "deploy/Dockerfile.fly"

[env]
  DJANGO_SETTINGS_MODULE = "whsxc.settings_fly"
  DJANGO_LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0  # Scale to zero for free tier

  # Health check removed to fix deployment timeout
  # [[http_service.checks]]
  #   grace_period = "30s"
  #   interval = "15s"
  #   method = "GET"
  #   path = "/admin/"
  #   protocol = "http"
  #   timeout = "10s"

[mounts]
  source = "whsxc_data"
  destination = "/app/data"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256  # Minimum for free tier

# [deploy]
#   release_command = "python manage.py migrate --settings=whsxc.settings_fly"

# Production scaling (uncomment for production)
# [[vm]]
#   cpu_kind = "shared" 
#   cpus = 2
#   memory_mb = 1024

# Development environment override (for dev.whsxc.com)
# [env.development]
#   DEBUG = "True"
#   DJANGO_LOG_LEVEL = "DEBUG"